### ISSUE TITLE
Add strshorten

### ISSUE THREAD

**Issue by pbtrung** [r-lyeh/stdstring.h#2]
Convert from utf16 to utf8 string on Windows.
Motivation: many Windows APIs take `wchar_t *` and return `wchar_t *` at the same time. The returned value has to be converted to utf8 string to have a consistent cross-platform interface. `stb` has both `stb_from_utf8` and `stb_to_utf8`. 
I would like to use this in my projects.
Thanks.

**Comment by r-lyeh** [comment]
I have pushed a quick fix. Let me know if it helps :)

**Comment by pbtrung** [comment]
Not working yet because of [#1](https://github.com/r-lyeh/stdstring.h/issues/1)

**Comment by r-lyeh** [comment]
Likely fix for #1

**Comment by pbtrung** [comment]
Working now.
Thanks.
